
version: 2

models:
  - name: raw_contact
    description: "my sample of contact data"
    columns:
      - name: ID_PERS
        description: "The primary key for this table"
        data_tests:
          - unique


  - name: raw_contract
    description: "my sample of contract data "
    columns:
      - name: ID_CONT
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
